apiVersion: v1
kind: Service
metadata:
  name: tinykv-client
  namespace: default
spec:
  clusterIP: 10.233.58.226
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - nodePort: 31256
      port: 6380
      protocol: TCP
      targetPort: 6380
  selector:
    app: tinykv-client
  sessionAffinity: None
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinykv-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tinykv-client  # 必须与 template.metadata.labels 一致
  template:
    metadata:
      labels:
        app: tinykv-client # 必须包含 selector.matchLabels 的标签
    spec:
      containers:
      - name: tinykv
        image: villanel/tinykv-client:latest
        command: ["/usr/local/bin/tinykv-client"]
        args:
        - "-path=tinyschedule.default.svc.cluster.local:2379"
        - "-host=0.0.0.0"
        ports:
        - containerPort: 6380
          name: client
        - containerPort: 2380
          name: peer
